services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tapicenter-web
    restart: always
    ports:
      - "5025:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
