name: CI/CD Deployment

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p ~/catalogos/${{ github.event.repository.name }}
            cd ~/catalogos/${{ github.event.repository.name }}

            git fetch origin ${{ github.ref_name }}
            git checkout ${{ github.ref_name }} || git checkout -b ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}

            DOCKER_BUILDKIT=1 docker compose build --no-cache

            docker compose up -d
